Added New IPS
os-fpga/IP_Catalog pull request #271
Opened 2024-08-04 16:54 UTC by bilal458

1. AXI DDR SDRAM
2. AXI SDRAM
3. AHB SRAM

2024-08-05 06:50 UTC, moinijaz approved these changes

2024-08-05 06:51 UTC, moinijaz requested changes
remove IP.log files

2024-08-06 11:44 UTC, bilal458 commented
> remove IP.log files

Done.

2024-08-06 11:50 UTC, moinijaz approved these changes

2024-08-06 12:04 UTC, merged